spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tsm_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: dev_password
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
logging:
  level:
    root: info
    com.tsm: debug
    
server:
  port: 8080