server:
  port: 8080

spring:
  application:
    name: tsm-gateway
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # 认证服务路由
        - id: tsm-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # 用户服务路由
        - id: tsm-user
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        
        # 权限服务路由
        - id: tsm-permission
          uri: http://localhost:8083
          predicates:
            - Path=/api/permission/**,/api/role/**
          filters:
            - StripPrefix=1
        
        # 静态资源路由
        - id: tsm-web
          uri: http://localhost:8084
          predicates:
            - Path=/static/**,/,/login,/index,/user/**,/permission/**,/profile
          filters:
            - StripPrefix=0
      
      # 全局过滤器配置
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
        - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
        - AddResponseHeader=Access-Control-Allow-Headers, *
        - AddResponseHeader=Access-Control-Max-Age, 3600

# 负载均衡配置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

# 日志配置
logging:
  level:
    com.tsm.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true